-- 코드를 입력하세요
SELECT FLAVOR FROM (SELECT FIRST_HALF.FLAVOR, TOTAL_ORDER, INGREDIENT_TYPE
FROM FIRST_HALF
LEFT JOIN ICECREAM_INFO 
ON ICECREAM_INFO.FLAVOR = FIRST_HALF.FLAVOR) as t3
WHERE t3.TOTAL_ORDER>3000 
AND t3.INGREDIENT_TYPE = "fruit_based"
ORDER BY t3.TOTAL_ORDER desc