-- 코드를 입력하세요
# 리뷰 평균 : 리뷰 점수 / 레스토랑 id별 리뷰 개수 
SELECT A.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO A 
JOIN REST_REVIEW B ON A.REST_ID = B.REST_ID
GROUP BY B.REST_ID
HAVING ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC
